apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mysql.github.io/mysql-operator/
    chart: mysql-operator
    targetRevision: 2.2.6
    helm:
      parameters:
        - name: image.repository
          value: container-registry.oracle.com/mysql/community-operator
        - name: image.tag
          value: 9.5.0-2.2.6-aarch64
        - name: nodeSelector.kubernetes\.io/arch
          value: arm64
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true